export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_FILE_UPLOAD_REQUEST = 'USER_FILE_UPLOAD_REQUEST'
export const USER_FILE_UPLOAD_SUCCESS = 'USER_FILE_UPLOAD_SUCCESS'
export const USER_FILE_UPLOAD_FAIL = 'USER_FILE_UPLOAD_FAIL'

export const USER_FETCH_DATA_REQUEST = 'USER_FETCH_DATA_REQUEST'
export const USER_FETCH_DATA_SUCCESS = 'USER_FETCH_DATA_SUCCESS'
export const USER_FETCH_DATA_FAIL = 'USER_FETCH_DATA_FAIL'